# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marvin_pb2 as marvin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marvin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarvinServiceStub:
    """============================================================================
    Service Definition
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/marvin.MarvinService/Connect',
                request_serializer=marvin__pb2.AgentMessage.SerializeToString,
                response_deserializer=marvin__pb2.ControlMessage.FromString,
                _registered_method=True)


class MarvinServiceServicer:
    """============================================================================
    Service Definition
    ============================================================================

    """

    def Connect(self, request_iterator, context):
        """Bi-directional stream for Marvin agent to connect to control plane.
        Lifecycle:
        1. Marvin sends Register (once)
        2. Control plane responds with Registered or RegistrationRejected
        3. Marvin sends periodic Heartbeat
        4. Control plane sends ExecuteCapability, Disconnect, or UpdateConfig
        5. Marvin sends CapabilityResult, LogEvent, StatusUpdate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarvinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=marvin__pb2.AgentMessage.FromString,
                    response_serializer=marvin__pb2.ControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marvin.MarvinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marvin.MarvinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarvinService:
    """============================================================================
    Service Definition
    ============================================================================

    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/marvin.MarvinService/Connect',
            marvin__pb2.AgentMessage.SerializeToString,
            marvin__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
