# Generated by Django 5.2.17 on 2026-09-27 15:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checks", "0001_initial"),
        ("core", "0003_organization_email_domain_organizationinvitation"),
        ("llm", "0003_llmprovider_cost_per_1m_input_tokens_and_more"),
        ("marvins", "0011_capability_needs_re_embedding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("interval", "Interval"), ("cron", "Cron")], max_length=20
                    ),
                ),
                (
                    "schedule_expression",
                    models.CharField(
                        help_text="e.g. '60' for interval seconds, or '0 9 * * *' for cron",
                        max_length=255,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("ai_assisted", "AI Assisted"),
                            ("autonomous", "Autonomous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "evaluation_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rules and thresholds for deterministic evaluation",
                    ),
                ),
                (
                    "notification_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action configuration: channels, conditions, recipients",
                    ),
                ),
                (
                    "execution_budget",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Max iterations, token limits, timeout settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "llm_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="llm.llmprovider",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="core.organization",
                    ),
                ),
                (
                    "target_scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="marvins.targetscope",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="CheckExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("queued", "Queued"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "health_state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("evaluation_result", models.JSONField(blank=True, default=dict)),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Collected capability results and LLM context",
                    ),
                ),
                (
                    "resolved_targets",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Marvin IDs and metadata at execution time",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=Decimal("0.00"), max_digits=14),
                ),
                ("actions_triggered", models.JSONField(blank=True, default=dict)),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="checks.check",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("teams", "Teams"),
                            ("alertmanager", "Alertmanager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="checks.check",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="checks.checkexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckHealthState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("state_changed_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("consecutive_successes", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_state",
                        to="checks.check",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "definition_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Immutable snapshot of Check config at creation time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="checks.check",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="checkexecution",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="checks.checkversion",
            ),
        ),
        migrations.AddIndex(
            model_name="checkexecution",
            index=models.Index(
                fields=["check", "execution_status"], name="checks_chec_check_i_5a5ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkexecution",
            index=models.Index(
                fields=["check", "health_state"], name="checks_chec_check_i_088092_idx"
            ),
        ),
    ]
