# Generated by Django 5.2.17 on 2026-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="System prompt or instructions for the LLM when evaluating this check. Used in AI-Assisted and Autonomous modes.",
            ),
        ),
    ]
