# Generated by Django 5.2.17 on 2026-10-03 21:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0003_check_instructions"),
        ("marvins", "0011_capability_needs_re_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckCapabilityExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("capability_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=Decimal("0.00"), max_digits=14),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_executions",
                        to="checks.checkexecution",
                    ),
                ),
                (
                    "marvin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_capability_executions",
                        to="marvins.marvin",
                    ),
                ),
                (
                    "target_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_capability_executions",
                        to="marvins.resolvedtargetset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["check_execution", "status"], name="checks_chec_check_e_ff2870_idx"
                    )
                ],
            },
        ),
    ]
