# Generated by Django 5.2.17 on 2026-10-03 22:40

from django.db import migrations


def migrate_execution_budget_forward(apps, schema_editor):
    Check = apps.get_model("checks", "Check")
    for check in Check.objects.all().iterator():
        budget = check.execution_budget or {}
        if not budget:
            check.execution_budget = {
                "max_executions_per_session": 100,
                "max_targets_per_session": 200,
                "max_concurrent_executions": 5,
                "executions_used": 0,
                "targets_used": 0,
                "concurrent_running": 0,
                "max_tokens_per_session": 0,
                "max_cost_per_session": "0.00",
                "max_context_tokens": 0,
                "tokens_used": 0,
                "cost_used": "0.00",
                "context_tokens_used": 0,
            }
            check.save(update_fields=["execution_budget"])
            continue

        if "max_iterations" in budget:
            new_budget = {
                "max_executions_per_session": budget.pop("max_iterations"),
                "max_targets_per_session": 200,
                "max_concurrent_executions": 5,
                "executions_used": 0,
                "targets_used": 0,
                "concurrent_running": 0,
                "max_tokens_per_session": 0,
                "max_cost_per_session": "0.00",
                "max_context_tokens": 0,
                "tokens_used": 0,
                "cost_used": "0.00",
                "context_tokens_used": 0,
            }
            check.execution_budget = new_budget
            check.save(update_fields=["execution_budget"])


def migrate_execution_budget_reverse(apps, schema_editor):
    Check = apps.get_model("checks", "Check")
    for check in Check.objects.all().iterator():
        budget = check.execution_budget or {}
        if not budget:
            check.execution_budget = {"max_iterations": 100}
            check.save(update_fields=["execution_budget"])
            continue

        if "max_iterations" in budget:
            continue

        new_budget = {"max_iterations": budget.get("max_executions_per_session", 100)}
        check.execution_budget = new_budget
        check.save(update_fields=["execution_budget"])


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0004_checkcapabilityexecution"),
    ]

    operations = [
        migrations.RunPython(
            migrate_execution_budget_forward,
            migrate_execution_budget_reverse,
        ),
    ]
