# Generated by Django 5.2.17 on 2026-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0020_delete_non_autonomous_checks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkhealthstate",
            name="check",
        ),
        migrations.RemoveField(
            model_name="check",
            name="evaluation_config",
        ),
        migrations.RemoveField(
            model_name="check",
            name="execution_mode",
        ),
        migrations.AlterField(
            model_name="check",
            name="instructions",
            field=models.TextField(
                blank=True, help_text="Instructions for the LLM when evaluating this check."
            ),
        ),
        migrations.DeleteModel(
            name="CheckCapabilityExecution",
        ),
        migrations.DeleteModel(
            name="CheckHealthState",
        ),
    ]
