# Generated by Django 5.2.17 on 2026-10-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0021_remove_checkhealthstate_check_and_more"),
        ("personalities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="personality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checks",
                to="personalities.personality",
            ),
        ),
    ]
