# Generated by Django 5.2.17 on 2026-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0022_check_personality"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="notification_policy_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of notification policy to use. Leave blank for org default.",
                max_length=255,
            ),
        ),
    ]
