# Generated by Django 5.2.17 on 2026-10-07 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0023_check_notification_policy_name"),
        ("core", "0003_organization_email_domain_organizationinvitation"),
        ("llm", "0003_llmprovider_cost_per_1m_input_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="schedule_expression",
            field=models.CharField(
                blank=True,
                help_text="e.g. '60' for interval seconds, or '0 9 * * *' for cron",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="check",
            name="schedule_type",
            field=models.CharField(
                choices=[("interval", "Interval"), ("cron", "Cron"), ("event", "Event")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CheckReceiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_type", models.CharField(default="alertmanager", max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "secret_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 hash of webhook secret", max_length=64
                    ),
                ),
                (
                    "admission_mode",
                    models.CharField(
                        choices=[("always", "Always"), ("ai_gated", "AI Gated")], max_length=20
                    ),
                ),
                ("gating_prompt", models.TextField(blank=True)),
                ("max_active_executions", models.PositiveIntegerField(default=1)),
                ("dedup_window_seconds", models.PositiveIntegerField(default=300)),
                ("fail_open_on_timeout", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_llm_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_receivers",
                        to="llm.llmprovider",
                    ),
                ),
                (
                    "check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="checks.check",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_receivers",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiverEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("source_type", models.CharField(default="alertmanager", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("firing", "Firing"), ("resolved", "Resolved")], max_length=20
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("normalized_payload", models.JSONField(default=dict)),
                ("correlation_identity", models.CharField(blank=True, max_length=500)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("normalized", "Normalized"),
                            ("deduplicated", "Deduplicated"),
                            ("correlated", "Correlated"),
                            ("admission_decided", "Admission Decided"),
                            ("started", "Started"),
                            ("attached", "Attached"),
                            ("suppressed", "Suppressed"),
                            ("failed", "Failed"),
                            ("resolved", "Resolved"),
                        ],
                        default="received",
                        max_length=30,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_events",
                        to="checks.check",
                    ),
                ),
                (
                    "check_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiver_events",
                        to="checks.checkexecution",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="checks.checkreceiver",
                    ),
                ),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_events",
                        to="checks.receiverevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiverAdmissionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("suppress_duplicate", "Suppress Duplicate"),
                            ("suppress_correlated", "Suppress Correlated"),
                            ("suppress_low_value", "Suppress Low Value"),
                            ("defer", "Defer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("candidate_investigations", models.JSONField(default=dict)),
                ("timed_out", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_decisions",
                        to="checks.receiverevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="receiverevent",
            index=models.Index(
                fields=["receiver", "external_fingerprint"], name="checks_rece_receive_8f2819_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiverevent",
            index=models.Index(
                fields=["receiver", "disposition"], name="checks_rece_receive_f3c7a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiverevent",
            index=models.Index(fields=["check_execution"], name="checks_rece_check_e_f061cc_idx"),
        ),
    ]
