# Generated by Django 5.2.17 on 2026-09-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mcp_api_token_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the MCP API token for this organization.",
                max_length=255,
            ),
        ),
    ]
