# Generated by Django 5.2.17 on 2026-08-30 18:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("ollama", "Ollama (Cloud or local)"),
                            ("openai", "OpenAI"),
                            ("openai_compat", "OpenAI-compatible (vLLM, etc.)"),
                            ("anthropic", "Anthropic"),
                        ],
                        default="ollama",
                        max_length=30,
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, help_text="e.g. https://ollama.com/v1", max_length=500
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="Store encrypted in production.", max_length=500
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="temperature, max_tokens, top_p"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_providers",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("organization",),
                        name="one_default_llm_per_org",
                    )
                ],
            },
        ),
    ]
