# Generated by Django 5.2.17 on 2026-08-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmprovider",
            old_name="api_key",
            new_name="_api_key_encrypted",
        ),
        migrations.AlterField(
            model_name="llmprovider",
            name="_api_key_encrypted",
            field=models.CharField(
                blank=True,
                db_column="api_key",
                help_text="Encrypted at rest via Fernet.",
                max_length=500,
            ),
        ),
    ]
