# Generated by Django 5.2.17 on 2026-09-26 20:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_rename_llmprovider_api_key_to_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="cost_per_1m_input_tokens",
            field=models.DecimalField(decimal_places=6, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="cost_per_1m_output_tokens",
            field=models.DecimalField(decimal_places=6, default=Decimal("0.00"), max_digits=12),
        ),
    ]
