# Generated by Django 5.2.17 on 2026-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_llmprovider_cost_per_1m_input_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="is_jev",
            field=models.BooleanField(
                default=False,
                help_text="Whether this provider uses the JEV (/v1/systemone) API instead of standard chat completions.",
            ),
        ),
    ]
