# Generated by Django 5.2.17 on 2026-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organization_email_domain_organizationinvitation"),
        ("llm", "0004_llmprovider_is_jev"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="is_jev_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this provider is the organization's default JEV provider for admission gates.",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmprovider",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_jev_default", True)),
                fields=("organization",),
                name="one_jev_default_per_org",
            ),
        ),
    ]
