# Generated by Django 5.2.17 on 2026-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("troubleshooting_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
