# Generated by Django 5.2.17 on 2026-08-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marvins", "0004_capability_keywords"),
        ("troubleshooting_sessions", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcall",
            name="labels",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="toolcall",
            name="marvin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_calls",
                to="marvins.marvin",
            ),
        ),
        migrations.AddField(
            model_name="toolcall",
            name="timeout_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
