# Generated by Django 5.2.17 on 2026-08-30 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("troubleshooting_sessions", "0004_toolcall_labels_toolcall_marvin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchitectureRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("fulfilled", "Fulfilled")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("diagram", models.FileField(blank=True, null=True, upload_to="architecture/")),
                ("markdown", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="architecture_requests",
                        to="troubleshooting_sessions.thread",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
