# Generated by Django 5.2.17 on 2026-08-30 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("troubleshooting_sessions", "0005_architecturerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("thinking", "Thinking"),
                            ("tool_call_started", "Tool Call Started"),
                            ("tool_result", "Tool Result"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_events",
                        to="troubleshooting_sessions.thread",
                    ),
                ),
                (
                    "tool_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="troubleshooting_sessions.toolcall",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
