# Generated by Django 5.2.17 on 2026-09-12 14:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marvins", "0006_capability_execution_policy_and_more"),
        ("troubleshooting_sessions", "0006_agentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcall",
            name="execution_mode",
            field=models.CharField(
                choices=[("single", "Single"), ("fanout", "Fan-out")],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="toolcall",
            name="policy_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="ExecutionPolicy at time of dispatch (immutable audit).",
            ),
        ),
        migrations.AddField(
            model_name="toolcall",
            name="target_set",
            field=models.ForeignKey(
                blank=True,
                help_text="The resolved target set used for this execution.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_calls",
                to="marvins.resolvedtargetset",
            ),
        ),
        migrations.AddField(
            model_name="tsession",
            name="execution_budget",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Session-level execution budget. See SessionBudget schema.",
            ),
        ),
        migrations.AddField(
            model_name="tsession",
            name="target_scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional scope constraining all executions in this session.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tsessions",
                to="marvins.targetscope",
            ),
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "result_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Index within the fan-out result array."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marvin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marvins.marvin",
                    ),
                ),
                (
                    "tool_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="troubleshooting_sessions.toolcall",
                    ),
                ),
            ],
            options={
                "ordering": ["result_index"],
                "indexes": [
                    models.Index(
                        fields=["tool_call", "status"], name="troubleshoo_tool_ca_52101d_idx"
                    ),
                    models.Index(
                        fields=["tool_call", "result_index"], name="troubleshoo_tool_ca_f4e9c4_idx"
                    ),
                ],
            },
        ),
    ]
