# Generated by Django 5.2.17 on 2026-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("troubleshooting_sessions", "0008_threadmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra LLM-specific data: tool_call_id, tool_calls array, name, etc.",
            ),
        ),
    ]
