# Generated by Django 5.2.17 on 2026-09-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_rename_llmprovider_api_key_to_encrypted"),
        ("troubleshooting_sessions", "0009_message_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tsession",
            name="llm_provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional LLM provider override for this session. Falls back to org default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tsessions",
                to="llm.llmprovider",
            ),
        ),
    ]
