# Generated by Django 5.2.17 on 2026-09-26 20:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("troubleshooting_sessions", "0010_tsession_llm_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="input_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="cost",
            field=models.DecimalField(decimal_places=6, default=Decimal("0.00"), max_digits=12),
        ),
    ]
