# Generated by Django 5.2.17 on 2026-09-26 20:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("troubleshooting_sessions", "0011_message_tokens_and_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="tsession",
            name="total_input_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tsession",
            name="total_output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tsession",
            name="total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tsession",
            name="total_cost",
            field=models.DecimalField(decimal_places=6, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="tsession",
            name="context_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Approximate tokens in the current conversation context.",
            ),
        ),
    ]
