# Generated by Django 5.2.17 on 2026-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("troubleshooting_sessions", "0013_message_model_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tsession",
            old_name="context_tokens",
            new_name="cumulative_context_tokens",
        ),
        migrations.AlterField(
            model_name="tsession",
            name="cumulative_context_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Cumulative sum of all tokens consumed in the session."
            ),
        ),
    ]
