# Generated by Django 5.2.17 on 2026-10-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalities", "0001_initial"),
        ("troubleshooting_sessions", "0015_tsession_is_autonomous"),
    ]

    operations = [
        migrations.AddField(
            model_name="tsession",
            name="personality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tsessions",
                to="personalities.personality",
            ),
        ),
    ]
