from collections.abc import Iterable
from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

CASCADE: object
SET_NULL: object

class Model: ...

class Manager(Generic[_T]):
    def create(self, **kwargs: Any) -> _T: ...
    def get(self, **kwargs: Any) -> _T: ...
    def get_or_create(self, **kwargs: Any) -> tuple[_T, bool]: ...
    def filter(self, **kwargs: Any) -> Any: ...
    def exclude(self, **kwargs: Any) -> Any: ...
    def none(self) -> Any: ...
    def all(self) -> Any: ...

class Field:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class UUIDField(Field): ...
class ForeignKey(Field): ...
class CharField(Field): ...
class DateTimeField(Field): ...
class JSONField(Field): ...
class TextField(Field): ...
class SlugField(Field): ...
class ManyToManyField(Field): ...

class TextChoices:
    choices: Iterable[Any]
