# Generated by Django 5.2.17 on 2026-09-22 19:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.marvins.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_organization_mcp_api_token_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Textual description of the infrastructure. Used for embedding search.",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("testing", "Testing"),
                        ],
                        default="production",
                        help_text="Deployment environment this design represents.",
                        max_length=20,
                    ),
                ),
                (
                    "mermaid_topology",
                    models.TextField(
                        blank=True,
                        help_text="Mermaid diagram source describing the infrastructure topology.",
                    ),
                ),
                (
                    "marvin_selector",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON label selector dict (same format as TargetScope.selector). AND semantics across keys. Example: {'labels': {'env': 'production', 'team': 'platform'}}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_document",
                    models.TextField(
                        blank=True,
                        help_text="Canonical retrieval-oriented document constructed from metadata.",
                    ),
                ),
                (
                    "search_document_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Monotonic version of search_document. Triggers re-embedding on change.",
                    ),
                ),
                (
                    "embedding",
                    apps.marvins.fields.VectorField(
                        blank=True, help_text="Vector embedding of search_document.", null=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Embedding model used (e.g. 'text-embedding-3-small').",
                        max_length=100,
                    ),
                ),
                (
                    "embedding_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Embedding generation version (monotonic, increments on model change).",
                    ),
                ),
                (
                    "needs_re_embedding",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when search_document_version > embedding_version; set by save().",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infrastructure_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infrastructure_designs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organization", "name")},
            },
        ),
    ]
