# Generated by Django 5.2.17 on 2026-09-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infradesigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructuredesign",
            name="marvin_selector",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON label selector dict (same format as TargetScope.selector). AND semantics across keys.",
            ),
        ),
    ]
