from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any

def defn(cls: type[Any]) -> type[Any]: ...
def run(fn: Callable[..., Any]) -> Callable[..., Any]: ...
def signal(fn: Callable[..., Any]) -> Callable[..., Any]: ...
def query(fn: Callable[..., Any]) -> Callable[..., Any]: ...
async def execute_activity(name: str, *args: Any, **kwargs: Any) -> Any: ...
async def wait_condition(fn: Callable[[], bool], *args: Any, **kwargs: Any) -> None: ...

class _Unsafe:
    def imports_passed_through(self) -> AbstractContextManager[None]: ...

unsafe: _Unsafe
logger: Any
