# Generated by Django 5.2.17 on 2026-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marvins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marvin",
            name="agent_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="marvin",
            name="arch",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="marvin",
            name="availability_zone",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="marvin",
            name="capability_configs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="marvin",
            name="hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="marvin",
            name="labels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="marvin",
            name="local_ip",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="marvin",
            name="os",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="marvin",
            name="os_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="marvin",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="marvin",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="marvin",
            name="vm_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
