# Generated by Django 5.2.17 on 2026-08-30 11:39

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.marvins.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("marvins", "0002_marvin_agent_version_marvin_arch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarvinRegistrationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=apps.marvins.models._generate_marvin_key,
                        editable=False,
                        help_text="Auto-generated alphanumeric registration key for Marvin agents.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional descriptive name for this key (e.g., 'Production Cluster').",
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvin_registration_keys",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
