# Generated by Django 5.2.17 on 2026-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marvins", "0003_marvinregistrationkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="keywords",
            field=models.JSONField(
                blank=True, default=list, help_text="Search keywords for find_tools"
            ),
        ),
    ]
