# Generated by Django 5.2.17 on 2026-09-06 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("marvins", "0004_capability_keywords"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "config_json_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema that every Resource of this type must satisfy.",
                    ),
                ),
                (
                    "capability_names",
                    models.JSONField(
                        default=list,
                        help_text="List of capability names that can use this resource (e.g. ['kubernetes']).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarvinConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "global_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Marvin-wide settings (e.g. log_level, default_timeout_seconds).",
                    ),
                ),
                (
                    "capability_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Capability-specific overrides set from the control plane.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marvin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_config",
                        to="marvins.marvin",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Connection parameters validated against ResourceType.config_json_schema.",
                    ),
                ),
                (
                    "secrets_encrypted",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sensitive values encrypted at rest (optional, v2).",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.organization",
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="marvins.resourcetype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="MarvinResourceAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attached_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marvin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_attachments",
                        to="marvins.marvin",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marvin_attachments",
                        to="marvins.resource",
                    ),
                ),
            ],
            options={
                "unique_together": {("marvin", "resource")},
            },
        ),
        migrations.AddField(
            model_name="marvin",
            name="attached_resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="marvins",
                through="marvins.MarvinResourceAttachment",
                to="marvins.resource",
            ),
        ),
    ]
