# Generated by Django 5.2.17 on 2026-09-12 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization_mcp_api_token_hash"),
        ("marvins", "0005_resourcetype_marvinconfig_resource_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="execution_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Server-side execution limits. See ExecutionPolicy schema.",
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="execution_scope",
            field=models.CharField(
                choices=[
                    ("marvin-local", "Marvin Local"),
                    ("host", "Host"),
                    ("cluster", "Cluster"),
                    ("namespace", "Namespace"),
                    ("service", "Service"),
                    ("environment", "Environment"),
                ],
                default="marvin-local",
                help_text="Logical scope this capability operates on.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="selection_strategy",
            field=models.CharField(
                choices=[
                    ("one", "One"),
                    ("all", "All"),
                    ("preferred", "Preferred"),
                    ("leader", "Leader"),
                    ("quorum", "Quorum"),
                ],
                default="one",
                help_text="How many executors to select from eligible Marvins.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("cluster", "Cluster"),
                    ("namespace", "Namespace"),
                    ("service", "Service"),
                    ("host", "Host"),
                    ("environment", "Environment"),
                    ("generic", "Generic"),
                ],
                default="generic",
                help_text="What kind of logical boundary this resource represents.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TargetScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "selector",
                    models.JSONField(
                        default=dict,
                        help_text="JSON TargetSelector dict. AND semantics across keys.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_scopes",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ResolvedTargetSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "selector",
                    models.JSONField(
                        default=dict, help_text="The selector that produced this set."
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=list,
                        help_text="List of Marvin UUIDs at resolution time. Immutable.",
                    ),
                ),
                (
                    "snapshot_metadata",
                    models.JSONField(
                        default=dict, help_text="Summary: count, sample labels, fanout_class, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="TTL after which this snapshot is considered stale."
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_target_sets",
                        to="marvins.capability",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_target_sets",
                        to="core.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_target_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_target_sets",
                        to="marvins.targetscope",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "expires_at"], name="marvins_res_organiz_d9e0e1_idx"
                    ),
                    models.Index(
                        fields=["capability", "created_at"], name="marvins_res_capabil_3c508e_idx"
                    ),
                ],
            },
        ),
    ]
