# Generated by Django 5.2.17 on 2026-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marvins", "0006_capability_execution_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Alternative names and abbreviations. List of strings.",
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="provider",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "Capability provider (e.g. kafka, kubernetes, network)."
                    " Denormalized from name prefix."
                ),
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="search_document",
            field=models.TextField(
                blank=True,
                help_text="Canonical retrieval-oriented document constructed from metadata.",
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="search_document_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monotonic version of search_document. Triggers re-embedding on change.",
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured tags for filtering. List of strings.",
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="use_cases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Retrieval-oriented 'useful for' descriptions. List of strings.",
            ),
        ),
    ]
