# Generated by Django 5.2.17 on 2026-09-12 23:00

from django.db import connection, migrations


def create_pgvector_extension(apps, schema_editor):
    """Create pgvector extension if running on PostgreSQL as superuser."""
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT rolsuper FROM pg_roles WHERE rolname = current_user;")
        is_superuser = cursor.fetchone()[0]
        if not is_superuser:
            return
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")


def drop_pgvector_extension(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT rolsuper FROM pg_roles WHERE rolname = current_user;")
        is_superuser = cursor.fetchone()[0]
        if not is_superuser:
            return
        cursor.execute("DROP EXTENSION IF EXISTS pg_trgm;")
        cursor.execute("DROP EXTENSION IF EXISTS vector;")


class Migration(migrations.Migration):
    dependencies = [
        ("marvins", "0007_add_discovery_metadata"),
    ]

    operations = [
        migrations.RunPython(create_pgvector_extension, reverse_code=drop_pgvector_extension),
    ]
