# Generated by Django 5.2.17 on 2026-09-12 21:49

from django.db import migrations, models

import apps.marvins.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marvins", "0008_add_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="embedding",
            field=apps.marvins.fields.VectorField(
                blank=True, help_text="Vector embedding of search_document.", null=True
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="embedding_model",
            field=models.CharField(
                blank=True,
                help_text="Embedding model used (e.g. 'text-embedding-3-small').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="embedding_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Embedding generation version (monotonic, increments on model change).",
            ),
        ),
    ]
