# Generated by Django 5.2.17 on 2026-09-13 00:48

from django.db import migrations, models


def backfill_needs_re_embedding(apps, schema_editor):
    Capability = apps.get_model("marvins", "Capability")
    Capability.objects.filter(search_document_version__gt=models.F("embedding_version")).update(
        needs_re_embedding=True
    )


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("marvins", "0010_backfill_provider_search_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="needs_re_embedding",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when search_document_version > embedding_version; set by save().",
            ),
        ),
        migrations.RunPython(backfill_needs_re_embedding, reverse_backfill),
    ]
