# pyright: reportAttributeAccessIssue=false

# Generated by Django 5.2.17 on 2026-10-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider_type", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("json_schema", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="notificationchannel",
            name="_credentials_encrypted",
            field=models.TextField(
                blank=True,
                db_column="credentials",
                help_text="Encrypted JSON dict of secret fields.",
            ),
        ),
    ]
